### ISSUE TITLE
cf-networking-release ignoring garden allow_networks configuration

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry/cf-networking-release#14]
Hi,
I deployed `cf-networking-release` today with `cf-release 265` and `diego-release 1.19`. When `cf-networking-release` is successfully deployed, the configuration section of 

```yaml
garden:
    mtu: 1426
    allow_networks:
    - 172.16.100.0/24
    - 172.16.101.0/24
```

Is completely ignored and the communication to the defined networks fails. Is there a trick in the deployment to avoid this behaviour?
