### ISSUE TITLE
selecting all active subnets: pq: relation \"subnets\" does not exist

### ISSUE THREAD

**Issue by schmidtsv** [cloudfoundry/cf-networking-release#29]
Thanks for submitting an issue to `cf-networking-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

I deployed cf-networking release as configured in cf-deployment, using an external postgresql94l as Data backend. While the Silk Controller starts, the Cells, which contain the silk-daemon fails when starting. Looking into the silk-daemon, I see the following error, which is also displayed on the silk-controllers:

```
{"timestamp":"1512762188.908506393","source":"cfnetworking.silk-daemon","message":"cfnetworking.silk-daemon.http-client","log_level":2,"data":{"body":"{\"error\": \"getting lease for underlay ip: pq: relation \"subnets\" does not exist\"}","code":500,"error":"{\"error\": \"getting lease for underlay ip: pq: relation \"subnets\" does not exist\"}"}}
```

## Context

I have a cloud foundry to which I wanted to add container networking, I added Silk, deployed, and it failed. I have verified that:

- credentials are correct
- db url is correct
- the db is reachable
- I can log in using the url and the credentials to log in
- tables are present in the database

Database on the PG instance:
```
containernetworking=> \dt
                   List of relations
 Schema |      Name       | Type  |        Owner        
--------+-----------------+-------+---------------------
 public | destinations    | table | containernetworking
 public | gorp_lock       | table | containernetworking
 public | gorp_migrations | table | containernetworking
 public | groups          | table | containernetworking
 public | policies        | table | containernetworking
```

## Steps to Reproduce
Add those snippets (which are apart from db config the same as in vanilla cf-deployment) to a cf-deployment which does not contain cf-networking
Manifest snippet on the diego-api:

```
  - name: silk-controller
    release: cf-networking
    properties:
      cf_networking:
        silk_controller:
          ca_cert: ((silk_controller.ca))
          server_cert: ((silk_controller.certificate))
          server_key: ((silk_controller.private_key))
          database:
            type: postgres
            username: containernetworking
            password: ((/a9s_pg_container-networking_password))
            host: a9s-pg-psql-master-alias.node.dc1.consul
            port: 5432
            name: containernetworking
        silk_daemon:
          ca_cert: ((silk_daemon.ca))
          client_cert: ((silk_daemon.certificate))
          client_key: ((silk_daemon.private_key))
```

cell-manifest-snippet:
```
  - name: garden-cni
    release: cf-networking
  - name: netmon
    release: cf-networking
  - name: vxlan-policy-agent
    release: cf-networking
    properties:
      cf_networking:
        vxlan_policy_agent:
          ca_cert: ((network_policy_client.ca))
          client_cert: ((network_policy_client.certificate))
          client_key: ((network_policy_client.private_key))
  - name: silk-daemon
    release: cf-networking
    properties:
      cf_networking:
        silk_daemon:
          ca_cert: ((silk_daemon.ca))
          client_cert: ((silk_daemon.certificate))
          client_key: ((silk_daemon.private_key))
  - name: cni
```

Hit deploy with a psql94 as data store

## Expected result

I can use container networking and the deployment succeeds

## Current result

Cell Fails, due to silk-daemon not starting, silk-controller is running, but throws errors because the relation 'subnets' does not exist

```
mestamp":"1512755942.645250082","source":"cfnetworking.silk-controller","message":"cfnetworking.silk-controller.request.leases-acquire.getting lease for underlay ip: pq: relation \"subnets\" does not exist","log_level":2,"data":{"error":"getting lease for underlay ip: pq: relation \"subnets\" does not exist","method":"PUT","request":"/leases/acquire","session":"647.1"}}
{"timestamp":"1512755959.055695534","source":"cfnetworking.silk-controller","message":"cfnetworking.silk-controller.metric-getter","log_level":2,"data":{"error":"selecting all subnets: pq: relation \"subnets\" does not exist","source":"totalLeases"}}
{"timestamp":"1512755959.063234806","source":"cfnetworking.silk-controller","message":"cfnetworking.silk-controller.metric-getter","log_level":2,"data":{"error":"selecting all subnets: pq: relation \"subnets\" does not exist","source":"freeLeases"}}
{"timestamp":"1512755959.083369732","source":"cfnetworking.silk-controller","message":"cfnetworking.silk-controller.metric-getter","log_level":2,"data":{"error":"selecting all active subnets: pq: relation \"subnets\" does not exist","source":"staleLeases"}}
{"timestamp":"1512755982.123170137","source":"cfnetworking.silk-controller","message":"cfnetworking.silk-controller.request.leases-acquire.getting lease for underlay ip: pq: relation \"subnets\" does not exist","log_level":2,"data":{"error":"getting lease for underlay ip: pq: relation \"subnets\" does not exist","method":"PUT","request":"/leases/acquire","session":"661.1"}}
{"timestamp":"1512755989.093193769","source":"cfnetworking.silk-controller","message":"cfnetworking.silk-controller.metric-getter","log_level":2,"data":{"error":"selecting all subnets: pq: relation \"subnets\" does not exist","source":"totalLeases"}}
{"timestamp":"1512755989.101576567","source":"cfnetworking.silk-controller","message":"cfnetworking.silk-controller.metric-getter","log_level":2,"data":{"error":"selecting all subnets: pq: relation \"subnets\" does not exist","source":"freeLeases"}}
{"timestamp":"1512755989.113017321","source":"cfnetworking.silk-controller","message":"cfnetworking.silk-controller.metric-getter","log_level":2,"data":{"error":"selecting all active subnets: pq: relation \"subnets\" does not exist","source":"staleLeases"}}
```

## Possible Fix

maybe it forgets to create the table? so creating it should fix it?
